# Endpoint FindAllEvents
### 
GET http://localhost:3000/events
Content-Type: application/json  

# Endpoint  FindOneEvent
### 
GET http://localhost:3000/events/1
Content-Type: application/json  

# Endpoint FindOneEvent
### 
GET http://localhost:3000/events/practice
Content-Type: application/json  
 

# Endpoint  
### 
POST http://localhost:3000/events
Content-Type: application/json 

{   
    "name": "Shopping",
    "description": "Let's go shopping",
    "when": "2022-10-17T13:00:00",
    "address": "Street 50, WallStreet Center"
}

# Endpoint  
### 
POST http://localhost:3000/events
Content-Type: application/json 

{   
    "name": "Pafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
    "description": "Clean Code",
    "when": "10/07/2022",
    "address": "google-meet-sd-gdd"
}

# Endpoint  
### 
PATCH http://localhost:3000/events/1
Content-Type: application/json  

{   
    "name": "Shopping",
    "description": "Let's go shopping",
    "when": "2022-10-17T13:00:00",
    "address": "Street 50, WallStreet Center"
}

# Endpoint  
### 
DELETE http://localhost:3000/events/7
Content-Type: application/json  

{}
