# Endpoint FindAllEvents
### 
GET http://localhost:3000/events?page=4
Content-Type: application/json  

# Endpoint  FindOneEvent
### 
GET http://localhost:3000/events/9
Content-Type: application/json  

# Endpoint 
### 
GET http://localhost:3000/events/practice
Content-Type: application/json  
 

# Endpoint 
### 
GET http://localhost:3000/events/practice_2
Content-Type: application/json  
 

 # Endpoint 
### 
GET http://localhost:3000/events/practice_3
Content-Type: application/json  

# Endpoint 
### 
GET http://localhost:3000/events/practice_4
Content-Type: application/json  
 

# Endpoint 
### 
GET http://localhost:3000/events/practice_5
Content-Type: application/json  
 

# Endpoint 
### 
GET http://localhost:3000/events/cascade
Content-Type: application/json  
 

# Endpoint GetUserByToken
### 
GET http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoYXJsZXMyMDIyIiwic3ViIjoyLCJpYXQiOjE2NTY2NDYwNDYsImV4cCI6MTY1NjY0OTY0Nn0.b9I1L-Gfjt7gq-JfstlL5F55Uo4awU5SQQdX9G-za3g
 

# Endpoint 
### 
POST http://localhost:3000/school/create
Content-Type: application/json  


# Endpoint RemoveSubjectOrTeacher
### 
POST http://localhost:3000/school/remove
Content-Type: application/json  
 


# Endpoint Login
### 
POST http://localhost:3000/auth/login
Content-Type: application/json  

{
    "username": "touscool10",
    "password": "18501405"
}

# Endpoint CreateUser
### 
POST http://localhost:3000/users
Content-Type: application/json  

{
    "username": "charles2022",
    "email": "charles@gmail.com",
    "password": "18501405123",
    "retypedPassword": "18501405123",
    "firstName": "Charles",
    "lastName": "Abami"
}

# Endpoint HelloWorldInJapan
### 
GET http://localhost:3000/app/hello
Content-Type: application/json  
 

# Endpoint CreateEvent
### 
POST http://localhost:3000/events
Content-Type: application/json 

{   
    "name": "Shopping",
    "description": "Let's go shopping",
    "when": "2022-10-17T13:00:00",
    "address": "Street 50, WallStreet Center"
}

# Endpoint  CreateEvent
### 
POST http://localhost:3000/events
Content-Type: application/json 

{   
    "name": "Pafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
    "description": "Clean Code",
    "when": "10/07/2022",
    "address": "google-meet-sd-gdd"
}

# Endpoint  UpdateEvent
### 
PATCH http://localhost:3000/events/1
Content-Type: application/json  

{   
    "name": "Shopping",
    "description": "Let's go shopping",
    "when": "2022-10-17T13:00:00",
    "address": "Street 50, WallStreet Center"
}

# Endpoint  DeleteEvent
### 
DELETE http://localhost:3000/events/1
Content-Type: application/json  

{}
